.......

diff --git a/.woodpecker.yml b/.woodpecker.yml
--- a/.woodpecker.yml
+++ b/.woodpecker.yml
@@ -41,16 +41,16 @@ steps:
       - while read -r service; do [ -d "$CI_WORKSPACE/$service" ] || exit 22; done < services.order
 
       # Process services in order
-      - |
-        while read -r service; do
-          SERVICE_PATH="$CI_WORKSPACE/$service"
-
-          [ -f "$SERVICE_PATH/Dockerfile" ] || { echo "ERROR: Dockerfile missing in $SERVICE_PATH"; exit 23; }
-          [ -f "$SERVICE_PATH/build_firmware.sh" ] || { echo "ERROR: build_firmware.sh missing in $SERVICE_PATH"; exit 24; }
-          [ -f "$SERVICE_PATH/versions.json" ] || { echo "ERROR: versions.json missing in $SERVICE_PATH"; exit 25; }
-
-          echo "[INFO] All required files present in $service directory."
-        done < services.order
+#      - |
+#        while read -r service; do
+#          SERVICE_PATH="$CI_WORKSPACE/$service"
+#
+#          [ -f "$SERVICE_PATH/Dockerfile" ] || { echo "ERROR: Dockerfile missing in $SERVICE_PATH"; exit 23; }
+#          [ -f "$SERVICE_PATH/build_firmware.sh" ] || { echo "ERROR: build_firmware.sh missing in $SERVICE_PATH"; exit 24; }
+#          [ -f "$SERVICE_PATH/versions.json" ] || { echo "ERROR: versions.json missing in $SERVICE_PATH"; exit 25; }
+#
+#          echo "[INFO] All required files present in $service directory."
+#        done < services.order
 
 #  - name: Build and push containers
 #    image: docker:latest
