Changed steps order to optimize for cache usage.

diff --git a/micropython_esp-idf/Dockerfile b/micropython_esp-idf/Dockerfile
--- a/micropython_esp-idf/Dockerfile
+++ b/micropython_esp-idf/Dockerfile
@@ -14,16 +14,18 @@ RUN rm -rf /var/lib/apt/lists/*
 ARG MICROPYTHON_VERSION=
 RUN test -n "$MICROPYTHON_VERSION" || (echo "ERROR: MICROPYTHON_VERSION build-arg is required" && exit 1)
 
-ARG ESP_IDF_VERSION=
-RUN test -n "$ESP_IDF_VERSION" || (echo "ERROR: ESP_IDF_VERSION build-arg is required" && exit 1)
-
 WORKDIR /opt
 RUN git clone -b ${MICROPYTHON_VERSION} --recursive https://github.com/micropython/micropython.git
-RUN git clone -b ${ESP_IDF_VERSION} --recursive https://github.com/espressif/esp-idf.git
 
 WORKDIR /opt/micropython
 RUN git submodule update --init --recursive
 RUN make -C mpy-cross -j2
+
+ARG ESP_IDF_VERSION=
+RUN test -n "$ESP_IDF_VERSION" || (echo "ERROR: ESP_IDF_VERSION build-arg is required" && exit 1)
+
+WORKDIR /opt
+RUN git clone -b ${ESP_IDF_VERSION} --recursive https://github.com/espressif/esp-idf.git
 
 WORKDIR /opt/esp-idf
 RUN git submodule update --init --recursive
